; Sahayak — PlatformIO Configuration
; Two environments: field_node and base_station
; Flash with: pio run -e field_node -t upload
;             pio run -e base_station -t upload

[env:field_node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<field_node.cpp>
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    olikraus/U8g2@^2.34.22

[env:base_station]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<base_station.cpp>
lib_deps =
    bblanchon/ArduinoJson@^6.21.3
    olikraus/U8g2@^2.34.22
